sudo: required
services:
    - docker

before_install:
    - docker build -t ktandon1991/fe-docker-flow -f Dockerfile.dev .

script:
    - docker run -e CI=true ktandon1991/fe-docker-flow npm run test

